title: Yggdrasil 日志

content:
    header: Yggdrasil API
    common: 常规配置
    uuid_algorithm: UUID 生成算法
        v3: 与原盗版用户 UUID 一致【推荐】
        v4: 随机生成【想要同时兼容盗版登录的不要选】
        hint: 选择 Version 3 以获得对原盗版服务器的最佳兼容性。

    token_expire_1: 令牌暂时失效时间
    token_expire_2: 令牌完全失效时间
        discription: 分别指定 Token【暂时失效】与【完全失效】的过期时间（技术细节请参阅 http://t.cn/RHKshKe），单位为秒

    rate_limit: 登录/登出频率限制
      hint: 两次操作之间的时间间隔（毫秒）

    skin_domain: 额外白名单域名
      discrip
    
    